Repository jakubsepiolo2001/COM619-AE1, pull requests merged in 2023-12, with the labels that each got.

#56 Mysql connections
  docker-compose-dev.yml
  docker-compose.yml
  pom.xml
  server/init/setup.sql
  src/main/java/org/project/spring/SpringBootJspApplication.java
  src/main/java/org/project/spring/service/OpenAPIConfiguration.java
  src/main/java/org/project/spring/service/ServiceConfiguration.java
  src/main/java/org/project/user/model/User.java
  src/main/java/org/project/user/repository/PersistenceJPAConfig.java
  src/main/java/org/project/user/repository/UserRepository.java
  src/main/resources/application-dev.properties
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
  src/main/resources/log4j2.xml
  src/main/resources/persistence-app.properties
Labels: enhancement

#57 Https tiles
  src/main/resources/static/js/leaflet-src.js
  src/main/resources/static/js/leaflet.js
  src/main/resources/static/js/map/map.js
Labels: enhancement

#63 Documentation updates
  Documentation/Deployment_Diagram.jpg
  Documentation/team-info.md
Labels: documentation

#70 Update maven.yml (firefox support)
  .github/workflows/maven.yml
Labels: enhancement, Feature
