Repository jakubsepiolo2001/COM619-AE1, pull requests merged in 2023-11, with the labels that each got.

#17 Nginx reverse 443
  docker-compose.yml
  nbactions.xml
  server/certbot/conf/accounts/acme-v02.api.letsencrypt.org/directory/3227d8e67cd5fdf2aa6dae9a78967949/meta.json
  server/certbot/conf/accounts/acme-v02.api.letsencrypt.org/directory/3227d8e67cd5fdf2aa6dae9a78967949/private_key.json
  server/certbot/conf/accounts/acme-v02.api.letsencrypt.org/directory/3227d8e67cd5fdf2aa6dae9a78967949/regr.json
  server/certbot/conf/archive/com619-1-vm.uksouth.cloudapp.azure.com/cert1.pem
  server/certbot/conf/archive/com619-1-vm.uksouth.cloudapp.azure.com/cert2.pem
  server/certbot/conf/archive/com619-1-vm.uksouth.cloudapp.azure.com/cert3.pem
  server/certbot/conf/archive/com619-1-vm.uksouth.cloudapp.azure.com/cert4.pem
  server/certbot/conf/archive/com619-1-vm.uksouth.cloudapp.azure.com/chain1.pem
  server/certbot/conf/archive/com619-1-vm.uksouth.cloudapp.azure.com/chain2.pem
  server/certbot/conf/archive/com619-1-vm.uksouth.cloudapp.azure.com/chain3.pem
  server/certbot/conf/archive/com619-1-vm.uksouth.cloudapp.azure.com/chain4.pem
  server/certbot/conf/archive/com619-1-vm.uksouth.cloudapp.azure.com/fullchain1.pem
  server/certbot/conf/archive/com619-1-vm.uksouth.cloudapp.azure.com/fullchain2.pem
  server/certbot/conf/archive/com619-1-vm.uksouth.cloudapp.azure.com/fullchain3.pem
  server/certbot/conf/archive/com619-1-vm.uksouth.cloudapp.azure.com/fullchain4.pem
  server/certbot/conf/archive/com619-1-vm.uksouth.cloudapp.azure.com/privkey1.pem
  server/certbot/conf/archive/com619-1-vm.uksouth.cloudapp.azure.com/privkey2.pem
  server/certbot/conf/archive/com619-1-vm.uksouth.cloudapp.azure.com/privkey3.pem
  server/certbot/conf/archive/com619-1-vm.uksouth.cloudapp.azure.com/privkey4.pem
  server/certbot/conf/live/README
  server/certbot/conf/live/com619-1-vm.uksouth.cloudapp.azure.com/README
  server/certbot/conf/live/com619-1-vm.uksouth.cloudapp.azure.com/cert.pem
  server/certbot/conf/live/com619-1-vm.uksouth.cloudapp.azure.com/chain.pem
  server/certbot/conf/live/com619-1-vm.uksouth.cloudapp.azure.com/fullchain.pem
  server/certbot/conf/live/com619-1-vm.uksouth.cloudapp.azure.com/privkey.pem
  server/certbot/conf/renewal/com619-1-vm.uksouth.cloudapp.azure.com.conf
  server/nginx/default.conf
  server/nginx/old_default.conf
Labels: Feature

#19 Added technology plan
  Documentation/Technology_Plan_03-11-23.md
Labels: documentation

#18 Project plan
  Documentation/Project_Plan_19-10-23.md
Labels: documentation

#26 Nav bar changes
  src/main/java/org/project/user/controller/MVCController.java
  src/main/resources/application.properties
  src/main/webapp/WEB-INF/view/about.jsp
  src/main/webapp/WEB-INF/view/contact.jsp
  src/main/webapp/WEB-INF/view/error.jsp
  src/main/webapp/WEB-INF/view/footer.jsp
  src/main/webapp/WEB-INF/view/header.jsp
  src/main/webapp/WEB-INF/view/home.jsp
  src/main/webapp/WEB-INF/view/login.jsp
  src/main/webapp/WEB-INF/view/register.jsp
  src/main/webapp/WEB-INF/view/users.jsp
  src/main/webapp/WEB-INF/view/viewModifyUser.jsp
Labels: enhancement

#28 Initial seggregation works
  pom.xml
  src/main/java/org/project/config/ApiConfig.java
  src/main/resources/application-dev.properties
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
  src/main/resources/static/js/map/map.js
  src/main/webapp/WEB-INF/view/LeafletJsp.jsp
Labels: Feature

#30 User permissions
  src/main/java/org/project/map/controller/MapPointRestController.java
  src/main/java/org/project/user/controller/UserAndLoginController.java
  src/main/java/org/project/user/model/User.java
  src/main/resources/application-prod.properties
  src/main/resources/static/js/map/map.js
  src/main/resources/static/js/map/markers.js
  src/main/resources/static/js/map/pointsadmin.js
  src/main/webapp/WEB-INF/view/LeafletJsp.jsp
  src/main/webapp/WEB-INF/view/contact.jsp
  src/main/webapp/WEB-INF/view/footer.jsp
  src/main/webapp/WEB-INF/view/header.jsp
  src/main/webapp/WEB-INF/view/points.jsp
Labels: enhancement, Feature

#29 added deployment diagram
  Documentation/Deployment_Diagram.jpg
Labels: documentation

#33 Mysql container
  .gitignore
  docker-compose.yml
  server/init/setup.sql
Labels: Feature

#34 Research database services
  Documentation/Research/Database_Services.markdown
  Documentation/Research/README.md
Labels: documentation, Research

#55 nginx config file ammend for routes to status page
  server/nginx/default.conf
Labels: Feature
